### ISSUE TITLE
WebExt API to Override CSP

### ISSUE THREAD

**Issue by Riajyuu** [crimx/ext-saladict#369]
current version doesn't really override CSP, perhaps this is what you want:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript

**Comment by crimx** [comment]
Hi! Please elaborate on the issues you have with this extension.

**Comment by Riajyuu** [comment]
I mean full page translation of this extension doesn't work on any site with CSP. This is an approach.

**Comment by crimx** [comment]
Which full-page translation of this extension and on what sites?

**Comment by Riajyuu** [comment]
![image](https://user-images.githubusercontent.com/16912240/58394737-45d8c680-8034-11e9-894b-ac81e87b033f.png)

CSP sites are a number, GitHub is merelt an example.

Minimal exmaple: 

```
browser.contextMenus.onClicked.addListener(async (info, ignored) => {
    if (info.menuItemId === "scanQR") {
        try {
            await doScanQR('contextMenu');
            if (accountOverwrite === true) {
                handleOverwrite();
            }
        } catch (error) {
            if (error instanceof Error) {
                showErrorMsg(error.message);
            } else {
                showErrorMsg(typeof error === 'string' ? error : i18n.getMessage('background_qr_not_found'));
            }
        }
    } else if (info.menuItemId === "autfillOTP") {
        const tabInfo = await browser.tabs.query({ active: true });
        browser.tabs.executeScript(
            tabInfo[0].id,
            {
                code: `fillKeyToActiveEl()`,
            }
        )
    }
});
```

**Comment by crimx** [comment]
I see. This is how Saladict works actually(FYI [here](https://github.com/crimx/ext-saladict/blob/3317fab4d43eb34d8a4760303f8e5e36a696c7e7/src/background/context-menus.ts#L107-L135) and [here](https://github.com/crimx/ext-saladict/blob/dev/public/static/google-page-trans.js)). But in order to take advantage of the extension environment, one needs to decipher all the of server communication protocols and implement them all over again. I did this with the Youdao page translation(hence it works). Google is just too complicated. PR is welcomed though :smile: .
