### ISSUE TITLE
Feature request: Copy=Translate, just as the job done by CopyTranslator.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#912]
Hi,

I also tried the [CopyTranslator](https://github.com/CopyTranslator/CopyTranslator) which is similar to ext-saladict but it can be installed as a system's app. For the translation job, it listens the clipboard and automatically do the trick. This way, it doesn't need any global shortkey for system-wide translations. 

What do you think about the method?

Regards,
HY

**Comment by crimx** [comment]
I haven't tried it but theoretically you may run a daemon that triggers the extension global shortcut when pressing the copy shortcut.

Another way is to run a daemon that communicates to the extension through extension native messaging API, which I haven't got the time to take a closer look and implement.

**Comment by hongyi-zhao** [comment]
I also noted that ext-saladict is rather faster than CopyTranslator in giving the translation results. It seems both of these two projects are based on javascript, so I'm very confused why ext-saladict can have so high performance. Any hints?

**Comment by crimx** [comment]
You've raised a rather interesting question which I am afraid I don't have an answer for. I know the author of CopyTranslator who is a brilliant fella. I am sure both projects are doing their best in terms of performance and speed. There are just too many factors that could affect the result.

Since I did not take part in the CopyTranslator project, I am going to share some of the code design behind Saladict:

1. Saladict runs in browser. Many processes can be shared with normal web pages.
2. Saladict has its own [scaffolding](https://github.com/crimx/neutrino-webextension) for code minification and chunk splitting.
3. Modules in Saladict are lazy-loaded on demand. This improves initial rendering speed and reduces memory usage.
4. Saladict makes heavy use of Reactive Programming for controlling network requests, interpreting user input sequences and implementing many trivial yet intricate animations.
